files:
  include: assets/scss/**/*.scss
rules: 
  no-empty-rulesets: 1
  property-sort-order:
    - 1
    - 
      order: 'smacss'
  force-element-nesting: 0
  force-attribute-nesting: 0
  force-pseudo-nesting: 0
  no-qualifying-elements: 0
  class-name-format: 0
  mixins-before-declarations: 0
