env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  no-console:
    - off
  no-undef:
    - off
  no-unused-vars:
    - off
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
